-- Create profiles table tied to auth.users
create table if not exists profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text,
  full_name text,
  avatar_url text,
  created_at timestamptz default now()
);

-- Activities table to record user actions
create table if not exists activities (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  type text not null,
  payload jsonb,
  created_at timestamptz default now()
);

create index if not exists idx_activities_user_created_at on activities (user_id, created_at desc);

-- Enable RLS and example policies (run these in Supabase SQL editor after enabling RLS)
-- ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Users can manage their profile" ON profiles
--   USING ( auth.uid() = id )
--   WITH CHECK ( auth.uid() = id );